### ISSUE TITLE
Specifying `determine` for fingerprint but not similarity measure leads to exception

### ISSUE THREAD

**Issue by JacksonBurns** [VlachosGroup/AIMSim#244]
When specifying the fingerprint_type as determine but not the simliarity measure, there is an UnboundLocalError raised due to the logic [shown here](https://github.com/VlachosGroup/AIMSim/blob/ec27073e25a1903d48b5d55cf873fea8637d71e3/aimsim/tasks/task_manager.py#L87). only_valid_sdist should be read outside of both of these conditionals, I believe.
```
fingerprint_type: determine
measure_id_subsample: 0.05
only_valid_dist: False
is_verbose: 0
molecule_database: # can be any, will not get this far
molecule_database_source_type: excel
n_workers: auto
similarity_measure: tanimoto
sampling_ratio: 0.1
tasks:
  visualize_dataset:
    heatmap_plot_settings:
      annotate: false
      cmap: viridis
      plot_title: Molecule Database Pairwise Similarities
    similarity_plot_settings:
      plot_color: green
      plot_title: Molecule Database Similarity Distribution
```
